// flow-typed signature: 5864d2222614e8ab1f917b79ff749a76
// flow-typed version: <<STUB>>/@release-it/conventional-changelog_v^10.0.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@release-it/conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@release-it/conventional-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@release-it/conventional-changelog/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@release-it/conventional-changelog/index' {
  declare module.exports: $Exports<'@release-it/conventional-changelog'>;
}
declare module '@release-it/conventional-changelog/index.js' {
  declare module.exports: $Exports<'@release-it/conventional-changelog'>;
}
declare module '@release-it/conventional-changelog/test.js' {
  declare module.exports: $Exports<'@release-it/conventional-changelog/test'>;
}
