// flow-typed signature: cd86bd48c84432ee53aa34b8c3fe52a3
// flow-typed version: <<STUB>>/@commitlint/config-conventional_v^19.6.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-conventional'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-conventional' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/config-conventional/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/config-conventional/lib/index' {
  declare module.exports: $Exports<'@commitlint/config-conventional/lib'>;
}
declare module '@commitlint/config-conventional/lib/index.js' {
  declare module.exports: $Exports<'@commitlint/config-conventional/lib'>;
}
