// flow-typed signature: bf487dc0f58db0d802c1dbdb3bf29ff3
// flow-typed version: <<STUB>>/@commitlint/cz-commitlint_v^19.6.1/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/cz-commitlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/cz-commitlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/cz-commitlint/lib' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/Process' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/Question' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/SectionBody' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/SectionFooter' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/SectionHeader' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/services/getRuleQuestionConfig' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/store/defaultPromptConfigs' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/store/prompts' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/store/rules' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/types' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/utils/case-fn' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/utils/full-stop-fn' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/utils/leading-blank-fn' {
  declare module.exports: any;
}

declare module '@commitlint/cz-commitlint/lib/utils/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/cz-commitlint/lib/index' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib'>;
}
declare module '@commitlint/cz-commitlint/lib/index.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib'>;
}
declare module '@commitlint/cz-commitlint/lib/Process.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/Process'>;
}
declare module '@commitlint/cz-commitlint/lib/Question.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/Question'>;
}
declare module '@commitlint/cz-commitlint/lib/SectionBody.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/SectionBody'>;
}
declare module '@commitlint/cz-commitlint/lib/SectionFooter.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/SectionFooter'>;
}
declare module '@commitlint/cz-commitlint/lib/SectionHeader.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/SectionHeader'>;
}
declare module '@commitlint/cz-commitlint/lib/services/getRuleQuestionConfig.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/services/getRuleQuestionConfig'>;
}
declare module '@commitlint/cz-commitlint/lib/store/defaultPromptConfigs.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/store/defaultPromptConfigs'>;
}
declare module '@commitlint/cz-commitlint/lib/store/prompts.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/store/prompts'>;
}
declare module '@commitlint/cz-commitlint/lib/store/rules.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/store/rules'>;
}
declare module '@commitlint/cz-commitlint/lib/types.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/types'>;
}
declare module '@commitlint/cz-commitlint/lib/utils/case-fn.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/utils/case-fn'>;
}
declare module '@commitlint/cz-commitlint/lib/utils/full-stop-fn.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/utils/full-stop-fn'>;
}
declare module '@commitlint/cz-commitlint/lib/utils/leading-blank-fn.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/utils/leading-blank-fn'>;
}
declare module '@commitlint/cz-commitlint/lib/utils/rules.js' {
  declare module.exports: $Exports<'@commitlint/cz-commitlint/lib/utils/rules'>;
}
