// flow-typed signature: 310f87ae340775001f307a9e2a64a59b
// flow-typed version: <<STUB>>/compression-webpack-plugin_v^11.1.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compression-webpack-plugin/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compression-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'compression-webpack-plugin/dist'>;
}
declare module 'compression-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'compression-webpack-plugin/dist'>;
}
