// flow-typed signature: 33a10f49a9bb1f9611a228b50de59f3f
// flow-typed version: <<STUB>>/eslint-plugin-storybook_v^0.11.2/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-storybook/dist/configs/addon-interactions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/csf-strict' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/csf' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/flat/addon-interactions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/flat/csf-strict' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/flat/csf' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/flat/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/configs/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/await-interactions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/context-in-play-function' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/csf-component' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/default-exports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/hierarchy-separator' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/meta-inline-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/no-redundant-story-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/no-stories-of' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/no-title-property-in-meta' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/no-uninstalled-addons' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/prefer-pascal-case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/story-exports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/use-storybook-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/rules/use-storybook-testing-library' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/utils/ast' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/utils/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/utils/create-storybook-rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-storybook/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-storybook/dist/configs/addon-interactions.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/addon-interactions'>;
}
declare module 'eslint-plugin-storybook/dist/configs/csf-strict.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/csf-strict'>;
}
declare module 'eslint-plugin-storybook/dist/configs/csf.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/csf'>;
}
declare module 'eslint-plugin-storybook/dist/configs/flat/addon-interactions.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/flat/addon-interactions'>;
}
declare module 'eslint-plugin-storybook/dist/configs/flat/csf-strict.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/flat/csf-strict'>;
}
declare module 'eslint-plugin-storybook/dist/configs/flat/csf.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/flat/csf'>;
}
declare module 'eslint-plugin-storybook/dist/configs/flat/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/flat/recommended'>;
}
declare module 'eslint-plugin-storybook/dist/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/configs/recommended'>;
}
declare module 'eslint-plugin-storybook/dist/index' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist'>;
}
declare module 'eslint-plugin-storybook/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist'>;
}
declare module 'eslint-plugin-storybook/dist/rules/await-interactions.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/await-interactions'>;
}
declare module 'eslint-plugin-storybook/dist/rules/context-in-play-function.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/context-in-play-function'>;
}
declare module 'eslint-plugin-storybook/dist/rules/csf-component.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/csf-component'>;
}
declare module 'eslint-plugin-storybook/dist/rules/default-exports.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/default-exports'>;
}
declare module 'eslint-plugin-storybook/dist/rules/hierarchy-separator.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/hierarchy-separator'>;
}
declare module 'eslint-plugin-storybook/dist/rules/meta-inline-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/meta-inline-properties'>;
}
declare module 'eslint-plugin-storybook/dist/rules/no-redundant-story-name.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/no-redundant-story-name'>;
}
declare module 'eslint-plugin-storybook/dist/rules/no-stories-of.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/no-stories-of'>;
}
declare module 'eslint-plugin-storybook/dist/rules/no-title-property-in-meta.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/no-title-property-in-meta'>;
}
declare module 'eslint-plugin-storybook/dist/rules/no-uninstalled-addons.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/no-uninstalled-addons'>;
}
declare module 'eslint-plugin-storybook/dist/rules/prefer-pascal-case.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/prefer-pascal-case'>;
}
declare module 'eslint-plugin-storybook/dist/rules/story-exports.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/story-exports'>;
}
declare module 'eslint-plugin-storybook/dist/rules/use-storybook-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/use-storybook-expect'>;
}
declare module 'eslint-plugin-storybook/dist/rules/use-storybook-testing-library.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/rules/use-storybook-testing-library'>;
}
declare module 'eslint-plugin-storybook/dist/types/index' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/types'>;
}
declare module 'eslint-plugin-storybook/dist/types/index.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/types'>;
}
declare module 'eslint-plugin-storybook/dist/utils/ast.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/utils/ast'>;
}
declare module 'eslint-plugin-storybook/dist/utils/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/utils/constants'>;
}
declare module 'eslint-plugin-storybook/dist/utils/create-storybook-rule.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/utils/create-storybook-rule'>;
}
declare module 'eslint-plugin-storybook/dist/utils/index' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/utils'>;
}
declare module 'eslint-plugin-storybook/dist/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-storybook/dist/utils'>;
}
