// flow-typed signature: a8b65584dcd923256f1e760ae5df2e7e
// flow-typed version: <<STUB>>/eslint-mdx_v^3.1.5/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-mdx/lib/helpers' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib/meta' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib/parser' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib/sync' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib/tokens' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib/types' {
  declare module.exports: any;
}

declare module 'eslint-mdx/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-mdx/lib/helpers.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/helpers'>;
}
declare module 'eslint-mdx/lib/index' {
  declare module.exports: $Exports<'eslint-mdx/lib'>;
}
declare module 'eslint-mdx/lib/index.js' {
  declare module.exports: $Exports<'eslint-mdx/lib'>;
}
declare module 'eslint-mdx/lib/meta.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/meta'>;
}
declare module 'eslint-mdx/lib/parser.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/parser'>;
}
declare module 'eslint-mdx/lib/sync.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/sync'>;
}
declare module 'eslint-mdx/lib/tokens.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/tokens'>;
}
declare module 'eslint-mdx/lib/types.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/types'>;
}
declare module 'eslint-mdx/lib/worker.js' {
  declare module.exports: $Exports<'eslint-mdx/lib/worker'>;
}
