// flow-typed signature: ea02818006ef9f4661f55968ddbab751
// flow-typed version: <<STUB>>/eslint-plugin-cypress_v^4.1.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-cypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-cypress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-cypress/jest.config-legacy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/jest.config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/legacy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/config/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/flat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/assertion-before-screenshot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-assigning-return-values' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-async-before' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-async-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-debug' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-force' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-pause' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/no-unnecessary-waiting' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/require-data-selectors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/lib/rules/unsafe-to-chain-command' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/assertion-before-screenshot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-assigning-return-values' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-async-before' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-async-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-force' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-pause' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-unnecessary-waiting' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/require-data-selectors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/unsafe-to-chain-command' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/assertion-before-screenshot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-assigning-return-values' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-async-before' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-async-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-debug' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-force' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-pause' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/no-unnecessary-waiting' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/require-data-selectors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cypress/tests/lib/rules/unsafe-to-chain-command' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-cypress/jest.config-legacy.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/jest.config-legacy'>;
}
declare module 'eslint-plugin-cypress/jest.config.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/jest.config'>;
}
declare module 'eslint-plugin-cypress/legacy.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/legacy'>;
}
declare module 'eslint-plugin-cypress/lib/config/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/config/recommended'>;
}
declare module 'eslint-plugin-cypress/lib/flat.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/flat'>;
}
declare module 'eslint-plugin-cypress/lib/rules/assertion-before-screenshot.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/assertion-before-screenshot'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-assigning-return-values.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-assigning-return-values'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-async-before.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-async-before'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-async-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-async-tests'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-debug.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-debug'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-force.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-force'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-pause.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-pause'>;
}
declare module 'eslint-plugin-cypress/lib/rules/no-unnecessary-waiting.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/no-unnecessary-waiting'>;
}
declare module 'eslint-plugin-cypress/lib/rules/require-data-selectors.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/require-data-selectors'>;
}
declare module 'eslint-plugin-cypress/lib/rules/unsafe-to-chain-command.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/lib/rules/unsafe-to-chain-command'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/config.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/config'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/assertion-before-screenshot.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/assertion-before-screenshot'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-assigning-return-values.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/no-assigning-return-values'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-async-before.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/no-async-before'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-async-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/no-async-tests'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-force.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/no-force'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-pause.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/no-pause'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/no-unnecessary-waiting.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/no-unnecessary-waiting'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/require-data-selectors.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/require-data-selectors'>;
}
declare module 'eslint-plugin-cypress/tests-legacy/lib/rules/unsafe-to-chain-command.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests-legacy/lib/rules/unsafe-to-chain-command'>;
}
declare module 'eslint-plugin-cypress/tests/config.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/config'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/assertion-before-screenshot.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/assertion-before-screenshot'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-assigning-return-values.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-assigning-return-values'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-async-before.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-async-before'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-async-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-async-tests'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-debug.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-debug'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-force.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-force'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-pause.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-pause'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/no-unnecessary-waiting.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/no-unnecessary-waiting'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/require-data-selectors.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/require-data-selectors'>;
}
declare module 'eslint-plugin-cypress/tests/lib/rules/unsafe-to-chain-command.js' {
  declare module.exports: $Exports<'eslint-plugin-cypress/tests/lib/rules/unsafe-to-chain-command'>;
}
