// flow-typed signature: 5fd0b0d46c3275c404705977758ed86d
// flow-typed version: <<STUB>>/eslint-config-prettier_v^10.0.1/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-prettier/build/@typescript-eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/babel' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/bin/cli' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/bin/validators' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/prettier' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/react' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/standard' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/unicorn' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier/build/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-prettier/build/@typescript-eslint.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/@typescript-eslint'>;
}
declare module 'eslint-config-prettier/build/babel.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/babel'>;
}
declare module 'eslint-config-prettier/build/bin/cli.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/bin/cli'>;
}
declare module 'eslint-config-prettier/build/bin/validators.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/bin/validators'>;
}
declare module 'eslint-config-prettier/build/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/flowtype'>;
}
declare module 'eslint-config-prettier/build/index' {
  declare module.exports: $Exports<'eslint-config-prettier/build'>;
}
declare module 'eslint-config-prettier/build/index.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build'>;
}
declare module 'eslint-config-prettier/build/prettier.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/prettier'>;
}
declare module 'eslint-config-prettier/build/react.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/react'>;
}
declare module 'eslint-config-prettier/build/standard.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/standard'>;
}
declare module 'eslint-config-prettier/build/unicorn.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/unicorn'>;
}
declare module 'eslint-config-prettier/build/vue.js' {
  declare module.exports: $Exports<'eslint-config-prettier/build/vue'>;
}
