// flow-typed signature: a820ed63a5fb64309aac149cb6287ac3
// flow-typed version: <<STUB>>/express-static-gzip_v^2.2.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-static-gzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-static-gzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-static-gzip/util/encoding-selection' {
  declare module.exports: any;
}

declare module 'express-static-gzip/util/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-static-gzip/index' {
  declare module.exports: $Exports<'express-static-gzip'>;
}
declare module 'express-static-gzip/index.js' {
  declare module.exports: $Exports<'express-static-gzip'>;
}
declare module 'express-static-gzip/util/encoding-selection.js' {
  declare module.exports: $Exports<'express-static-gzip/util/encoding-selection'>;
}
declare module 'express-static-gzip/util/options.js' {
  declare module.exports: $Exports<'express-static-gzip/util/options'>;
}
