// flow-typed signature: c4dd7ec7af17d11df528b0c230667d14
// flow-typed version: <<STUB>>/globals_v^15.14.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'globals/index' {
  declare module.exports: $Exports<'globals'>;
}
declare module 'globals/index.js' {
  declare module.exports: $Exports<'globals'>;
}
