// flow-typed signature: 122c9913a5c3eca7e4c66c31c9a4cab7
// flow-typed version: <<STUB>>/knip_v5.42.2/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'knip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'knip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'knip/bin/knip-bun' {
  declare module.exports: any;
}

declare module 'knip/bin/knip' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/bash-parser' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/fallback' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/bun' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/bunx' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/npm' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/npx' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/pnpm' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/pnpx' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/package-manager/yarn' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/plugins' {
  declare module.exports: any;
}

declare module 'knip/dist/binaries/util' {
  declare module.exports: any;
}

declare module 'knip/dist/CacheConsultant' {
  declare module.exports: any;
}

declare module 'knip/dist/cli' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers/astro' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers/compilers' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers/mdx' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers/svelte' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers/types' {
  declare module.exports: any;
}

declare module 'knip/dist/compilers/vue' {
  declare module.exports: any;
}

declare module 'knip/dist/ConfigurationChief' {
  declare module.exports: any;
}

declare module 'knip/dist/ConfigurationValidator' {
  declare module.exports: any;
}

declare module 'knip/dist/ConsoleStreamer' {
  declare module.exports: any;
}

declare module 'knip/dist/constants' {
  declare module.exports: any;
}

declare module 'knip/dist/DependencyDeputy' {
  declare module.exports: any;
}

declare module 'knip/dist' {
  declare module.exports: any;
}

declare module 'knip/dist/IssueCollector' {
  declare module.exports: any;
}

declare module 'knip/dist/IssueFixer' {
  declare module.exports: any;
}

declare module 'knip/dist/issues/initializers' {
  declare module.exports: any;
}

declare module 'knip/dist/manifest/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/manifest' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/_template' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/_template/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/angular' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/angular/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/astro' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/ava' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/ava/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/babel/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/babel' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/babel/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/c8' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/capacitor' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/capacitor/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/changesets' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/changesets/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/commitizen' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/commitizen/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/commitlint' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/commitlint/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cspell' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cspell/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cucumber' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cucumber/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cypress/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cypress' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/cypress/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/dependency-cruiser' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/dotenv' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/drizzle' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/drizzle/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/eleventy/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/eleventy' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/eleventy/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/eslint/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/eslint' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/eslint/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/expo/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/expo' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/expo/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/gatsby' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/gatsby/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/github-actions' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/github-actions/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/glob' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/graphql-codegen' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/graphql-codegen/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/husky' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/jest/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/jest' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/jest/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/karma/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/karma' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/karma/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/ladle' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/ladle/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/lefthook' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/lint-staged' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/lint-staged/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/linthtml' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/linthtml/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/lockfile-lint' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/lost-pixel' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/markdownlint/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/markdownlint' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/markdownlint/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/metro' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/metro/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/mocha' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/mocha/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/moonrepo' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/moonrepo/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/msw' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/msw/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nest' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nest/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/netlify/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/netlify' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/netlify/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/next' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/node-test-runner' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/node' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nodemon' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/npm-package-json-lint' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/npm-package-json-lint/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nuxt' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nuxt/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nx' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nx/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nyc' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/nyc/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/oclif' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/oclif/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/playwright-ct' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/playwright-test' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/playwright' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/playwright/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/plop' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/postcss' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/postcss/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/preconstruct' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/preconstruct/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/prettier' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/prettier/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/react-cosmos' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/react-cosmos/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/release-it' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/release-it/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/remark' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/remark/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/remix' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/rollup' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/rsbuild' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/rsbuild/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/rspack' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/semantic-release' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/semantic-release/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/sentry' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/simple-git-hooks' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/simple-git-hooks/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/size-limit' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/storybook' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/storybook/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/stryker' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/stryker/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/stylelint' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/stylelint/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/svelte' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/syncpack' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/tailwind' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/travis' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/ts-node' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/tsup' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/tsup/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/tsx' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/typedoc' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/typedoc/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/typescript' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/unbuild' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/unbuild/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/unocss' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vercel-og' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vike' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vite' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vitest/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vitest' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vitest/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vue' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/vue/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/webdriver-io' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/webdriver-io/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/webpack' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/webpack/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/wireit' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/wireit/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/wrangler' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/wrangler/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/xo' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/xo/types' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/yarn' {
  declare module.exports: any;
}

declare module 'knip/dist/plugins/yorkie' {
  declare module.exports: any;
}

declare module 'knip/dist/PrincipalFactory' {
  declare module.exports: any;
}

declare module 'knip/dist/ProjectPrincipal' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/codeowners' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/compact' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/disclosure' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/json' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/markdown' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/symbols' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/util' {
  declare module.exports: any;
}

declare module 'knip/dist/reporters/watch' {
  declare module.exports: any;
}

declare module 'knip/dist/schema/plugins' {
  declare module.exports: any;
}

declare module 'knip/dist/types/args' {
  declare module.exports: any;
}

declare module 'knip/dist/types/cli' {
  declare module.exports: any;
}

declare module 'knip/dist/types/config' {
  declare module.exports: any;
}

declare module 'knip/dist/types/dependency-graph' {
  declare module.exports: any;
}

declare module 'knip/dist/types/exports' {
  declare module.exports: any;
}

declare module 'knip/dist/types/imports' {
  declare module.exports: any;
}

declare module 'knip/dist/types/issues' {
  declare module.exports: any;
}

declare module 'knip/dist/types/package-json' {
  declare module.exports: any;
}

declare module 'knip/dist/types/PluginNames' {
  declare module.exports: any;
}

declare module 'knip/dist/types/project' {
  declare module.exports: any;
}

declare module 'knip/dist/types/workspace' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/ast-helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/create-hosts' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/find-internal-references' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/get-imports-and-exports' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/resolve-module-names' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/SourceFile' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/SourceFileManager' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/dynamic-imports/importCall' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/dynamic-imports/importType' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/dynamic-imports' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/dynamic-imports/jsDocType' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/dynamic-imports/requireCall' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/dynamic-imports/resolveCall' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/exports/exportAssignment' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/exports/exportDeclaration' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/exports/exportKeyword' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/exports/exportsAccessExpression' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/exports' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/exports/moduleExportsAccessExpression' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/helpers' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/imports/importDeclaration' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/imports/importEqualsDeclaration' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/imports' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/imports/reExportDeclaration' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/scripts/bun' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/scripts/execa' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/scripts' {
  declare module.exports: any;
}

declare module 'knip/dist/typescript/visitors/scripts/zx' {
  declare module.exports: any;
}

declare module 'knip/dist/util/array' {
  declare module.exports: any;
}

declare module 'knip/dist/util/cli-arguments' {
  declare module.exports: any;
}

declare module 'knip/dist/util/create-workspace-graph' {
  declare module.exports: any;
}

declare module 'knip/dist/util/debug' {
  declare module.exports: any;
}

declare module 'knip/dist/util/dependency-graph' {
  declare module.exports: any;
}

declare module 'knip/dist/util/empty' {
  declare module.exports: any;
}

declare module 'knip/dist/util/errors' {
  declare module.exports: any;
}

declare module 'knip/dist/util/file-entry-cache' {
  declare module.exports: any;
}

declare module 'knip/dist/util/fs' {
  declare module.exports: any;
}

declare module 'knip/dist/util/get-included-issue-types' {
  declare module.exports: any;
}

declare module 'knip/dist/util/get-referenced-inputs' {
  declare module.exports: any;
}

declare module 'knip/dist/util/git' {
  declare module.exports: any;
}

declare module 'knip/dist/util/glob-core' {
  declare module.exports: any;
}

declare module 'knip/dist/util/glob' {
  declare module.exports: any;
}

declare module 'knip/dist/util/has-strictly-ns-references' {
  declare module.exports: any;
}

declare module 'knip/dist/util/input' {
  declare module.exports: any;
}

declare module 'knip/dist/util/is-identifier-referenced' {
  declare module.exports: any;
}

declare module 'knip/dist/util/jiti' {
  declare module.exports: any;
}

declare module 'knip/dist/util/loader' {
  declare module.exports: any;
}

declare module 'knip/dist/util/log' {
  declare module.exports: any;
}

declare module 'knip/dist/util/map-workspaces' {
  declare module.exports: any;
}

declare module 'knip/dist/util/modules' {
  declare module.exports: any;
}

declare module 'knip/dist/util/object' {
  declare module.exports: any;
}

declare module 'knip/dist/util/package-json' {
  declare module.exports: any;
}

declare module 'knip/dist/util/package-name' {
  declare module.exports: any;
}

declare module 'knip/dist/util/path' {
  declare module.exports: any;
}

declare module 'knip/dist/util/Performance' {
  declare module.exports: any;
}

declare module 'knip/dist/util/plugin-config' {
  declare module.exports: any;
}

declare module 'knip/dist/util/plugin' {
  declare module.exports: any;
}

declare module 'knip/dist/util/regex' {
  declare module.exports: any;
}

declare module 'knip/dist/util/remove-export' {
  declare module.exports: any;
}

declare module 'knip/dist/util/reporter' {
  declare module.exports: any;
}

declare module 'knip/dist/util/require' {
  declare module.exports: any;
}

declare module 'knip/dist/util/resolve' {
  declare module.exports: any;
}

declare module 'knip/dist/util/serialize' {
  declare module.exports: any;
}

declare module 'knip/dist/util/tag' {
  declare module.exports: any;
}

declare module 'knip/dist/util/to-source-path' {
  declare module.exports: any;
}

declare module 'knip/dist/util/trace' {
  declare module.exports: any;
}

declare module 'knip/dist/util/tsconfig-loader' {
  declare module.exports: any;
}

declare module 'knip/dist/util/unwrap-function' {
  declare module.exports: any;
}

declare module 'knip/dist/util/watch' {
  declare module.exports: any;
}

declare module 'knip/dist/util/workspace' {
  declare module.exports: any;
}

declare module 'knip/dist/version' {
  declare module.exports: any;
}

declare module 'knip/dist/WorkspaceWorker' {
  declare module.exports: any;
}

declare module 'knip/vendor/bash-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'knip/bin/knip-bun.js' {
  declare module.exports: $Exports<'knip/bin/knip-bun'>;
}
declare module 'knip/bin/knip.js' {
  declare module.exports: $Exports<'knip/bin/knip'>;
}
declare module 'knip/dist/binaries/bash-parser.js' {
  declare module.exports: $Exports<'knip/dist/binaries/bash-parser'>;
}
declare module 'knip/dist/binaries/fallback.js' {
  declare module.exports: $Exports<'knip/dist/binaries/fallback'>;
}
declare module 'knip/dist/binaries/index' {
  declare module.exports: $Exports<'knip/dist/binaries'>;
}
declare module 'knip/dist/binaries/index.js' {
  declare module.exports: $Exports<'knip/dist/binaries'>;
}
declare module 'knip/dist/binaries/package-manager/bun.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/bun'>;
}
declare module 'knip/dist/binaries/package-manager/bunx.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/bunx'>;
}
declare module 'knip/dist/binaries/package-manager/index' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager'>;
}
declare module 'knip/dist/binaries/package-manager/index.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager'>;
}
declare module 'knip/dist/binaries/package-manager/npm.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/npm'>;
}
declare module 'knip/dist/binaries/package-manager/npx.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/npx'>;
}
declare module 'knip/dist/binaries/package-manager/pnpm.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/pnpm'>;
}
declare module 'knip/dist/binaries/package-manager/pnpx.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/pnpx'>;
}
declare module 'knip/dist/binaries/package-manager/yarn.js' {
  declare module.exports: $Exports<'knip/dist/binaries/package-manager/yarn'>;
}
declare module 'knip/dist/binaries/plugins.js' {
  declare module.exports: $Exports<'knip/dist/binaries/plugins'>;
}
declare module 'knip/dist/binaries/util.js' {
  declare module.exports: $Exports<'knip/dist/binaries/util'>;
}
declare module 'knip/dist/CacheConsultant.js' {
  declare module.exports: $Exports<'knip/dist/CacheConsultant'>;
}
declare module 'knip/dist/cli.js' {
  declare module.exports: $Exports<'knip/dist/cli'>;
}
declare module 'knip/dist/compilers/astro.js' {
  declare module.exports: $Exports<'knip/dist/compilers/astro'>;
}
declare module 'knip/dist/compilers/compilers.js' {
  declare module.exports: $Exports<'knip/dist/compilers/compilers'>;
}
declare module 'knip/dist/compilers/index' {
  declare module.exports: $Exports<'knip/dist/compilers'>;
}
declare module 'knip/dist/compilers/index.js' {
  declare module.exports: $Exports<'knip/dist/compilers'>;
}
declare module 'knip/dist/compilers/mdx.js' {
  declare module.exports: $Exports<'knip/dist/compilers/mdx'>;
}
declare module 'knip/dist/compilers/svelte.js' {
  declare module.exports: $Exports<'knip/dist/compilers/svelte'>;
}
declare module 'knip/dist/compilers/types.js' {
  declare module.exports: $Exports<'knip/dist/compilers/types'>;
}
declare module 'knip/dist/compilers/vue.js' {
  declare module.exports: $Exports<'knip/dist/compilers/vue'>;
}
declare module 'knip/dist/ConfigurationChief.js' {
  declare module.exports: $Exports<'knip/dist/ConfigurationChief'>;
}
declare module 'knip/dist/ConfigurationValidator.js' {
  declare module.exports: $Exports<'knip/dist/ConfigurationValidator'>;
}
declare module 'knip/dist/ConsoleStreamer.js' {
  declare module.exports: $Exports<'knip/dist/ConsoleStreamer'>;
}
declare module 'knip/dist/constants.js' {
  declare module.exports: $Exports<'knip/dist/constants'>;
}
declare module 'knip/dist/DependencyDeputy.js' {
  declare module.exports: $Exports<'knip/dist/DependencyDeputy'>;
}
declare module 'knip/dist/index' {
  declare module.exports: $Exports<'knip/dist'>;
}
declare module 'knip/dist/index.js' {
  declare module.exports: $Exports<'knip/dist'>;
}
declare module 'knip/dist/IssueCollector.js' {
  declare module.exports: $Exports<'knip/dist/IssueCollector'>;
}
declare module 'knip/dist/IssueFixer.js' {
  declare module.exports: $Exports<'knip/dist/IssueFixer'>;
}
declare module 'knip/dist/issues/initializers.js' {
  declare module.exports: $Exports<'knip/dist/issues/initializers'>;
}
declare module 'knip/dist/manifest/helpers.js' {
  declare module.exports: $Exports<'knip/dist/manifest/helpers'>;
}
declare module 'knip/dist/manifest/index' {
  declare module.exports: $Exports<'knip/dist/manifest'>;
}
declare module 'knip/dist/manifest/index.js' {
  declare module.exports: $Exports<'knip/dist/manifest'>;
}
declare module 'knip/dist/plugins.js' {
  declare module.exports: $Exports<'knip/dist/plugins'>;
}
declare module 'knip/dist/plugins/_template/index' {
  declare module.exports: $Exports<'knip/dist/plugins/_template'>;
}
declare module 'knip/dist/plugins/_template/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/_template'>;
}
declare module 'knip/dist/plugins/_template/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/_template/types'>;
}
declare module 'knip/dist/plugins/angular/index' {
  declare module.exports: $Exports<'knip/dist/plugins/angular'>;
}
declare module 'knip/dist/plugins/angular/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/angular'>;
}
declare module 'knip/dist/plugins/angular/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/angular/types'>;
}
declare module 'knip/dist/plugins/astro/index' {
  declare module.exports: $Exports<'knip/dist/plugins/astro'>;
}
declare module 'knip/dist/plugins/astro/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/astro'>;
}
declare module 'knip/dist/plugins/ava/index' {
  declare module.exports: $Exports<'knip/dist/plugins/ava'>;
}
declare module 'knip/dist/plugins/ava/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/ava'>;
}
declare module 'knip/dist/plugins/ava/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/ava/types'>;
}
declare module 'knip/dist/plugins/babel/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/babel/helpers'>;
}
declare module 'knip/dist/plugins/babel/index' {
  declare module.exports: $Exports<'knip/dist/plugins/babel'>;
}
declare module 'knip/dist/plugins/babel/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/babel'>;
}
declare module 'knip/dist/plugins/babel/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/babel/types'>;
}
declare module 'knip/dist/plugins/c8/index' {
  declare module.exports: $Exports<'knip/dist/plugins/c8'>;
}
declare module 'knip/dist/plugins/c8/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/c8'>;
}
declare module 'knip/dist/plugins/capacitor/index' {
  declare module.exports: $Exports<'knip/dist/plugins/capacitor'>;
}
declare module 'knip/dist/plugins/capacitor/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/capacitor'>;
}
declare module 'knip/dist/plugins/capacitor/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/capacitor/types'>;
}
declare module 'knip/dist/plugins/changesets/index' {
  declare module.exports: $Exports<'knip/dist/plugins/changesets'>;
}
declare module 'knip/dist/plugins/changesets/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/changesets'>;
}
declare module 'knip/dist/plugins/changesets/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/changesets/types'>;
}
declare module 'knip/dist/plugins/commitizen/index' {
  declare module.exports: $Exports<'knip/dist/plugins/commitizen'>;
}
declare module 'knip/dist/plugins/commitizen/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/commitizen'>;
}
declare module 'knip/dist/plugins/commitizen/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/commitizen/types'>;
}
declare module 'knip/dist/plugins/commitlint/index' {
  declare module.exports: $Exports<'knip/dist/plugins/commitlint'>;
}
declare module 'knip/dist/plugins/commitlint/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/commitlint'>;
}
declare module 'knip/dist/plugins/commitlint/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/commitlint/types'>;
}
declare module 'knip/dist/plugins/cspell/index' {
  declare module.exports: $Exports<'knip/dist/plugins/cspell'>;
}
declare module 'knip/dist/plugins/cspell/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cspell'>;
}
declare module 'knip/dist/plugins/cspell/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cspell/types'>;
}
declare module 'knip/dist/plugins/cucumber/index' {
  declare module.exports: $Exports<'knip/dist/plugins/cucumber'>;
}
declare module 'knip/dist/plugins/cucumber/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cucumber'>;
}
declare module 'knip/dist/plugins/cucumber/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cucumber/types'>;
}
declare module 'knip/dist/plugins/cypress/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cypress/helpers'>;
}
declare module 'knip/dist/plugins/cypress/index' {
  declare module.exports: $Exports<'knip/dist/plugins/cypress'>;
}
declare module 'knip/dist/plugins/cypress/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cypress'>;
}
declare module 'knip/dist/plugins/cypress/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/cypress/types'>;
}
declare module 'knip/dist/plugins/dependency-cruiser/index' {
  declare module.exports: $Exports<'knip/dist/plugins/dependency-cruiser'>;
}
declare module 'knip/dist/plugins/dependency-cruiser/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/dependency-cruiser'>;
}
declare module 'knip/dist/plugins/dotenv/index' {
  declare module.exports: $Exports<'knip/dist/plugins/dotenv'>;
}
declare module 'knip/dist/plugins/dotenv/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/dotenv'>;
}
declare module 'knip/dist/plugins/drizzle/index' {
  declare module.exports: $Exports<'knip/dist/plugins/drizzle'>;
}
declare module 'knip/dist/plugins/drizzle/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/drizzle'>;
}
declare module 'knip/dist/plugins/drizzle/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/drizzle/types'>;
}
declare module 'knip/dist/plugins/eleventy/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/eleventy/helpers'>;
}
declare module 'knip/dist/plugins/eleventy/index' {
  declare module.exports: $Exports<'knip/dist/plugins/eleventy'>;
}
declare module 'knip/dist/plugins/eleventy/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/eleventy'>;
}
declare module 'knip/dist/plugins/eleventy/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/eleventy/types'>;
}
declare module 'knip/dist/plugins/eslint/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/eslint/helpers'>;
}
declare module 'knip/dist/plugins/eslint/index' {
  declare module.exports: $Exports<'knip/dist/plugins/eslint'>;
}
declare module 'knip/dist/plugins/eslint/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/eslint'>;
}
declare module 'knip/dist/plugins/eslint/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/eslint/types'>;
}
declare module 'knip/dist/plugins/expo/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/expo/helpers'>;
}
declare module 'knip/dist/plugins/expo/index' {
  declare module.exports: $Exports<'knip/dist/plugins/expo'>;
}
declare module 'knip/dist/plugins/expo/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/expo'>;
}
declare module 'knip/dist/plugins/expo/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/expo/types'>;
}
declare module 'knip/dist/plugins/gatsby/index' {
  declare module.exports: $Exports<'knip/dist/plugins/gatsby'>;
}
declare module 'knip/dist/plugins/gatsby/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/gatsby'>;
}
declare module 'knip/dist/plugins/gatsby/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/gatsby/types'>;
}
declare module 'knip/dist/plugins/github-actions/index' {
  declare module.exports: $Exports<'knip/dist/plugins/github-actions'>;
}
declare module 'knip/dist/plugins/github-actions/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/github-actions'>;
}
declare module 'knip/dist/plugins/github-actions/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/github-actions/types'>;
}
declare module 'knip/dist/plugins/glob/index' {
  declare module.exports: $Exports<'knip/dist/plugins/glob'>;
}
declare module 'knip/dist/plugins/glob/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/glob'>;
}
declare module 'knip/dist/plugins/graphql-codegen/index' {
  declare module.exports: $Exports<'knip/dist/plugins/graphql-codegen'>;
}
declare module 'knip/dist/plugins/graphql-codegen/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/graphql-codegen'>;
}
declare module 'knip/dist/plugins/graphql-codegen/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/graphql-codegen/types'>;
}
declare module 'knip/dist/plugins/husky/index' {
  declare module.exports: $Exports<'knip/dist/plugins/husky'>;
}
declare module 'knip/dist/plugins/husky/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/husky'>;
}
declare module 'knip/dist/plugins/index' {
  declare module.exports: $Exports<'knip/dist/plugins'>;
}
declare module 'knip/dist/plugins/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins'>;
}
declare module 'knip/dist/plugins/jest/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/jest/helpers'>;
}
declare module 'knip/dist/plugins/jest/index' {
  declare module.exports: $Exports<'knip/dist/plugins/jest'>;
}
declare module 'knip/dist/plugins/jest/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/jest'>;
}
declare module 'knip/dist/plugins/jest/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/jest/types'>;
}
declare module 'knip/dist/plugins/karma/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/karma/helpers'>;
}
declare module 'knip/dist/plugins/karma/index' {
  declare module.exports: $Exports<'knip/dist/plugins/karma'>;
}
declare module 'knip/dist/plugins/karma/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/karma'>;
}
declare module 'knip/dist/plugins/karma/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/karma/types'>;
}
declare module 'knip/dist/plugins/ladle/index' {
  declare module.exports: $Exports<'knip/dist/plugins/ladle'>;
}
declare module 'knip/dist/plugins/ladle/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/ladle'>;
}
declare module 'knip/dist/plugins/ladle/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/ladle/types'>;
}
declare module 'knip/dist/plugins/lefthook/index' {
  declare module.exports: $Exports<'knip/dist/plugins/lefthook'>;
}
declare module 'knip/dist/plugins/lefthook/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/lefthook'>;
}
declare module 'knip/dist/plugins/lint-staged/index' {
  declare module.exports: $Exports<'knip/dist/plugins/lint-staged'>;
}
declare module 'knip/dist/plugins/lint-staged/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/lint-staged'>;
}
declare module 'knip/dist/plugins/lint-staged/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/lint-staged/types'>;
}
declare module 'knip/dist/plugins/linthtml/index' {
  declare module.exports: $Exports<'knip/dist/plugins/linthtml'>;
}
declare module 'knip/dist/plugins/linthtml/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/linthtml'>;
}
declare module 'knip/dist/plugins/linthtml/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/linthtml/types'>;
}
declare module 'knip/dist/plugins/lockfile-lint/index' {
  declare module.exports: $Exports<'knip/dist/plugins/lockfile-lint'>;
}
declare module 'knip/dist/plugins/lockfile-lint/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/lockfile-lint'>;
}
declare module 'knip/dist/plugins/lost-pixel/index' {
  declare module.exports: $Exports<'knip/dist/plugins/lost-pixel'>;
}
declare module 'knip/dist/plugins/lost-pixel/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/lost-pixel'>;
}
declare module 'knip/dist/plugins/markdownlint/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/markdownlint/helpers'>;
}
declare module 'knip/dist/plugins/markdownlint/index' {
  declare module.exports: $Exports<'knip/dist/plugins/markdownlint'>;
}
declare module 'knip/dist/plugins/markdownlint/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/markdownlint'>;
}
declare module 'knip/dist/plugins/markdownlint/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/markdownlint/types'>;
}
declare module 'knip/dist/plugins/metro/index' {
  declare module.exports: $Exports<'knip/dist/plugins/metro'>;
}
declare module 'knip/dist/plugins/metro/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/metro'>;
}
declare module 'knip/dist/plugins/metro/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/metro/types'>;
}
declare module 'knip/dist/plugins/mocha/index' {
  declare module.exports: $Exports<'knip/dist/plugins/mocha'>;
}
declare module 'knip/dist/plugins/mocha/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/mocha'>;
}
declare module 'knip/dist/plugins/mocha/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/mocha/types'>;
}
declare module 'knip/dist/plugins/moonrepo/index' {
  declare module.exports: $Exports<'knip/dist/plugins/moonrepo'>;
}
declare module 'knip/dist/plugins/moonrepo/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/moonrepo'>;
}
declare module 'knip/dist/plugins/moonrepo/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/moonrepo/types'>;
}
declare module 'knip/dist/plugins/msw/index' {
  declare module.exports: $Exports<'knip/dist/plugins/msw'>;
}
declare module 'knip/dist/plugins/msw/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/msw'>;
}
declare module 'knip/dist/plugins/msw/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/msw/types'>;
}
declare module 'knip/dist/plugins/nest/index' {
  declare module.exports: $Exports<'knip/dist/plugins/nest'>;
}
declare module 'knip/dist/plugins/nest/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nest'>;
}
declare module 'knip/dist/plugins/nest/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nest/types'>;
}
declare module 'knip/dist/plugins/netlify/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/netlify/helpers'>;
}
declare module 'knip/dist/plugins/netlify/index' {
  declare module.exports: $Exports<'knip/dist/plugins/netlify'>;
}
declare module 'knip/dist/plugins/netlify/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/netlify'>;
}
declare module 'knip/dist/plugins/netlify/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/netlify/types'>;
}
declare module 'knip/dist/plugins/next/index' {
  declare module.exports: $Exports<'knip/dist/plugins/next'>;
}
declare module 'knip/dist/plugins/next/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/next'>;
}
declare module 'knip/dist/plugins/node-test-runner/index' {
  declare module.exports: $Exports<'knip/dist/plugins/node-test-runner'>;
}
declare module 'knip/dist/plugins/node-test-runner/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/node-test-runner'>;
}
declare module 'knip/dist/plugins/node/index' {
  declare module.exports: $Exports<'knip/dist/plugins/node'>;
}
declare module 'knip/dist/plugins/node/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/node'>;
}
declare module 'knip/dist/plugins/nodemon/index' {
  declare module.exports: $Exports<'knip/dist/plugins/nodemon'>;
}
declare module 'knip/dist/plugins/nodemon/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nodemon'>;
}
declare module 'knip/dist/plugins/npm-package-json-lint/index' {
  declare module.exports: $Exports<'knip/dist/plugins/npm-package-json-lint'>;
}
declare module 'knip/dist/plugins/npm-package-json-lint/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/npm-package-json-lint'>;
}
declare module 'knip/dist/plugins/npm-package-json-lint/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/npm-package-json-lint/types'>;
}
declare module 'knip/dist/plugins/nuxt/index' {
  declare module.exports: $Exports<'knip/dist/plugins/nuxt'>;
}
declare module 'knip/dist/plugins/nuxt/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nuxt'>;
}
declare module 'knip/dist/plugins/nuxt/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nuxt/types'>;
}
declare module 'knip/dist/plugins/nx/index' {
  declare module.exports: $Exports<'knip/dist/plugins/nx'>;
}
declare module 'knip/dist/plugins/nx/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nx'>;
}
declare module 'knip/dist/plugins/nx/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nx/types'>;
}
declare module 'knip/dist/plugins/nyc/index' {
  declare module.exports: $Exports<'knip/dist/plugins/nyc'>;
}
declare module 'knip/dist/plugins/nyc/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nyc'>;
}
declare module 'knip/dist/plugins/nyc/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/nyc/types'>;
}
declare module 'knip/dist/plugins/oclif/index' {
  declare module.exports: $Exports<'knip/dist/plugins/oclif'>;
}
declare module 'knip/dist/plugins/oclif/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/oclif'>;
}
declare module 'knip/dist/plugins/oclif/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/oclif/types'>;
}
declare module 'knip/dist/plugins/playwright-ct/index' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright-ct'>;
}
declare module 'knip/dist/plugins/playwright-ct/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright-ct'>;
}
declare module 'knip/dist/plugins/playwright-test/index' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright-test'>;
}
declare module 'knip/dist/plugins/playwright-test/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright-test'>;
}
declare module 'knip/dist/plugins/playwright/index' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright'>;
}
declare module 'knip/dist/plugins/playwright/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright'>;
}
declare module 'knip/dist/plugins/playwright/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/playwright/types'>;
}
declare module 'knip/dist/plugins/plop/index' {
  declare module.exports: $Exports<'knip/dist/plugins/plop'>;
}
declare module 'knip/dist/plugins/plop/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/plop'>;
}
declare module 'knip/dist/plugins/postcss/index' {
  declare module.exports: $Exports<'knip/dist/plugins/postcss'>;
}
declare module 'knip/dist/plugins/postcss/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/postcss'>;
}
declare module 'knip/dist/plugins/postcss/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/postcss/types'>;
}
declare module 'knip/dist/plugins/preconstruct/index' {
  declare module.exports: $Exports<'knip/dist/plugins/preconstruct'>;
}
declare module 'knip/dist/plugins/preconstruct/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/preconstruct'>;
}
declare module 'knip/dist/plugins/preconstruct/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/preconstruct/types'>;
}
declare module 'knip/dist/plugins/prettier/index' {
  declare module.exports: $Exports<'knip/dist/plugins/prettier'>;
}
declare module 'knip/dist/plugins/prettier/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/prettier'>;
}
declare module 'knip/dist/plugins/prettier/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/prettier/types'>;
}
declare module 'knip/dist/plugins/react-cosmos/index' {
  declare module.exports: $Exports<'knip/dist/plugins/react-cosmos'>;
}
declare module 'knip/dist/plugins/react-cosmos/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/react-cosmos'>;
}
declare module 'knip/dist/plugins/react-cosmos/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/react-cosmos/types'>;
}
declare module 'knip/dist/plugins/release-it/index' {
  declare module.exports: $Exports<'knip/dist/plugins/release-it'>;
}
declare module 'knip/dist/plugins/release-it/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/release-it'>;
}
declare module 'knip/dist/plugins/release-it/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/release-it/types'>;
}
declare module 'knip/dist/plugins/remark/index' {
  declare module.exports: $Exports<'knip/dist/plugins/remark'>;
}
declare module 'knip/dist/plugins/remark/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/remark'>;
}
declare module 'knip/dist/plugins/remark/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/remark/types'>;
}
declare module 'knip/dist/plugins/remix/index' {
  declare module.exports: $Exports<'knip/dist/plugins/remix'>;
}
declare module 'knip/dist/plugins/remix/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/remix'>;
}
declare module 'knip/dist/plugins/rollup/index' {
  declare module.exports: $Exports<'knip/dist/plugins/rollup'>;
}
declare module 'knip/dist/plugins/rollup/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/rollup'>;
}
declare module 'knip/dist/plugins/rsbuild/index' {
  declare module.exports: $Exports<'knip/dist/plugins/rsbuild'>;
}
declare module 'knip/dist/plugins/rsbuild/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/rsbuild'>;
}
declare module 'knip/dist/plugins/rsbuild/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/rsbuild/types'>;
}
declare module 'knip/dist/plugins/rspack/index' {
  declare module.exports: $Exports<'knip/dist/plugins/rspack'>;
}
declare module 'knip/dist/plugins/rspack/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/rspack'>;
}
declare module 'knip/dist/plugins/semantic-release/index' {
  declare module.exports: $Exports<'knip/dist/plugins/semantic-release'>;
}
declare module 'knip/dist/plugins/semantic-release/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/semantic-release'>;
}
declare module 'knip/dist/plugins/semantic-release/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/semantic-release/types'>;
}
declare module 'knip/dist/plugins/sentry/index' {
  declare module.exports: $Exports<'knip/dist/plugins/sentry'>;
}
declare module 'knip/dist/plugins/sentry/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/sentry'>;
}
declare module 'knip/dist/plugins/simple-git-hooks/index' {
  declare module.exports: $Exports<'knip/dist/plugins/simple-git-hooks'>;
}
declare module 'knip/dist/plugins/simple-git-hooks/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/simple-git-hooks'>;
}
declare module 'knip/dist/plugins/simple-git-hooks/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/simple-git-hooks/types'>;
}
declare module 'knip/dist/plugins/size-limit/index' {
  declare module.exports: $Exports<'knip/dist/plugins/size-limit'>;
}
declare module 'knip/dist/plugins/size-limit/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/size-limit'>;
}
declare module 'knip/dist/plugins/storybook/index' {
  declare module.exports: $Exports<'knip/dist/plugins/storybook'>;
}
declare module 'knip/dist/plugins/storybook/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/storybook'>;
}
declare module 'knip/dist/plugins/storybook/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/storybook/types'>;
}
declare module 'knip/dist/plugins/stryker/index' {
  declare module.exports: $Exports<'knip/dist/plugins/stryker'>;
}
declare module 'knip/dist/plugins/stryker/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/stryker'>;
}
declare module 'knip/dist/plugins/stryker/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/stryker/types'>;
}
declare module 'knip/dist/plugins/stylelint/index' {
  declare module.exports: $Exports<'knip/dist/plugins/stylelint'>;
}
declare module 'knip/dist/plugins/stylelint/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/stylelint'>;
}
declare module 'knip/dist/plugins/stylelint/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/stylelint/types'>;
}
declare module 'knip/dist/plugins/svelte/index' {
  declare module.exports: $Exports<'knip/dist/plugins/svelte'>;
}
declare module 'knip/dist/plugins/svelte/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/svelte'>;
}
declare module 'knip/dist/plugins/syncpack/index' {
  declare module.exports: $Exports<'knip/dist/plugins/syncpack'>;
}
declare module 'knip/dist/plugins/syncpack/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/syncpack'>;
}
declare module 'knip/dist/plugins/tailwind/index' {
  declare module.exports: $Exports<'knip/dist/plugins/tailwind'>;
}
declare module 'knip/dist/plugins/tailwind/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/tailwind'>;
}
declare module 'knip/dist/plugins/travis/index' {
  declare module.exports: $Exports<'knip/dist/plugins/travis'>;
}
declare module 'knip/dist/plugins/travis/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/travis'>;
}
declare module 'knip/dist/plugins/ts-node/index' {
  declare module.exports: $Exports<'knip/dist/plugins/ts-node'>;
}
declare module 'knip/dist/plugins/ts-node/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/ts-node'>;
}
declare module 'knip/dist/plugins/tsup/index' {
  declare module.exports: $Exports<'knip/dist/plugins/tsup'>;
}
declare module 'knip/dist/plugins/tsup/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/tsup'>;
}
declare module 'knip/dist/plugins/tsup/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/tsup/types'>;
}
declare module 'knip/dist/plugins/tsx/index' {
  declare module.exports: $Exports<'knip/dist/plugins/tsx'>;
}
declare module 'knip/dist/plugins/tsx/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/tsx'>;
}
declare module 'knip/dist/plugins/typedoc/index' {
  declare module.exports: $Exports<'knip/dist/plugins/typedoc'>;
}
declare module 'knip/dist/plugins/typedoc/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/typedoc'>;
}
declare module 'knip/dist/plugins/typedoc/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/typedoc/types'>;
}
declare module 'knip/dist/plugins/typescript/index' {
  declare module.exports: $Exports<'knip/dist/plugins/typescript'>;
}
declare module 'knip/dist/plugins/typescript/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/typescript'>;
}
declare module 'knip/dist/plugins/unbuild/index' {
  declare module.exports: $Exports<'knip/dist/plugins/unbuild'>;
}
declare module 'knip/dist/plugins/unbuild/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/unbuild'>;
}
declare module 'knip/dist/plugins/unbuild/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/unbuild/types'>;
}
declare module 'knip/dist/plugins/unocss/index' {
  declare module.exports: $Exports<'knip/dist/plugins/unocss'>;
}
declare module 'knip/dist/plugins/unocss/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/unocss'>;
}
declare module 'knip/dist/plugins/vercel-og/index' {
  declare module.exports: $Exports<'knip/dist/plugins/vercel-og'>;
}
declare module 'knip/dist/plugins/vercel-og/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vercel-og'>;
}
declare module 'knip/dist/plugins/vike/index' {
  declare module.exports: $Exports<'knip/dist/plugins/vike'>;
}
declare module 'knip/dist/plugins/vike/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vike'>;
}
declare module 'knip/dist/plugins/vite/index' {
  declare module.exports: $Exports<'knip/dist/plugins/vite'>;
}
declare module 'knip/dist/plugins/vite/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vite'>;
}
declare module 'knip/dist/plugins/vitest/helpers.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vitest/helpers'>;
}
declare module 'knip/dist/plugins/vitest/index' {
  declare module.exports: $Exports<'knip/dist/plugins/vitest'>;
}
declare module 'knip/dist/plugins/vitest/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vitest'>;
}
declare module 'knip/dist/plugins/vitest/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vitest/types'>;
}
declare module 'knip/dist/plugins/vue/index' {
  declare module.exports: $Exports<'knip/dist/plugins/vue'>;
}
declare module 'knip/dist/plugins/vue/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vue'>;
}
declare module 'knip/dist/plugins/vue/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/vue/types'>;
}
declare module 'knip/dist/plugins/webdriver-io/index' {
  declare module.exports: $Exports<'knip/dist/plugins/webdriver-io'>;
}
declare module 'knip/dist/plugins/webdriver-io/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/webdriver-io'>;
}
declare module 'knip/dist/plugins/webdriver-io/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/webdriver-io/types'>;
}
declare module 'knip/dist/plugins/webpack/index' {
  declare module.exports: $Exports<'knip/dist/plugins/webpack'>;
}
declare module 'knip/dist/plugins/webpack/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/webpack'>;
}
declare module 'knip/dist/plugins/webpack/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/webpack/types'>;
}
declare module 'knip/dist/plugins/wireit/index' {
  declare module.exports: $Exports<'knip/dist/plugins/wireit'>;
}
declare module 'knip/dist/plugins/wireit/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/wireit'>;
}
declare module 'knip/dist/plugins/wireit/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/wireit/types'>;
}
declare module 'knip/dist/plugins/wrangler/index' {
  declare module.exports: $Exports<'knip/dist/plugins/wrangler'>;
}
declare module 'knip/dist/plugins/wrangler/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/wrangler'>;
}
declare module 'knip/dist/plugins/wrangler/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/wrangler/types'>;
}
declare module 'knip/dist/plugins/xo/index' {
  declare module.exports: $Exports<'knip/dist/plugins/xo'>;
}
declare module 'knip/dist/plugins/xo/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/xo'>;
}
declare module 'knip/dist/plugins/xo/types.js' {
  declare module.exports: $Exports<'knip/dist/plugins/xo/types'>;
}
declare module 'knip/dist/plugins/yarn/index' {
  declare module.exports: $Exports<'knip/dist/plugins/yarn'>;
}
declare module 'knip/dist/plugins/yarn/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/yarn'>;
}
declare module 'knip/dist/plugins/yorkie/index' {
  declare module.exports: $Exports<'knip/dist/plugins/yorkie'>;
}
declare module 'knip/dist/plugins/yorkie/index.js' {
  declare module.exports: $Exports<'knip/dist/plugins/yorkie'>;
}
declare module 'knip/dist/PrincipalFactory.js' {
  declare module.exports: $Exports<'knip/dist/PrincipalFactory'>;
}
declare module 'knip/dist/ProjectPrincipal.js' {
  declare module.exports: $Exports<'knip/dist/ProjectPrincipal'>;
}
declare module 'knip/dist/reporters/codeowners.js' {
  declare module.exports: $Exports<'knip/dist/reporters/codeowners'>;
}
declare module 'knip/dist/reporters/compact.js' {
  declare module.exports: $Exports<'knip/dist/reporters/compact'>;
}
declare module 'knip/dist/reporters/disclosure.js' {
  declare module.exports: $Exports<'knip/dist/reporters/disclosure'>;
}
declare module 'knip/dist/reporters/index' {
  declare module.exports: $Exports<'knip/dist/reporters'>;
}
declare module 'knip/dist/reporters/index.js' {
  declare module.exports: $Exports<'knip/dist/reporters'>;
}
declare module 'knip/dist/reporters/json.js' {
  declare module.exports: $Exports<'knip/dist/reporters/json'>;
}
declare module 'knip/dist/reporters/markdown.js' {
  declare module.exports: $Exports<'knip/dist/reporters/markdown'>;
}
declare module 'knip/dist/reporters/symbols.js' {
  declare module.exports: $Exports<'knip/dist/reporters/symbols'>;
}
declare module 'knip/dist/reporters/util.js' {
  declare module.exports: $Exports<'knip/dist/reporters/util'>;
}
declare module 'knip/dist/reporters/watch.js' {
  declare module.exports: $Exports<'knip/dist/reporters/watch'>;
}
declare module 'knip/dist/schema/plugins.js' {
  declare module.exports: $Exports<'knip/dist/schema/plugins'>;
}
declare module 'knip/dist/types/args.js' {
  declare module.exports: $Exports<'knip/dist/types/args'>;
}
declare module 'knip/dist/types/cli.js' {
  declare module.exports: $Exports<'knip/dist/types/cli'>;
}
declare module 'knip/dist/types/config.js' {
  declare module.exports: $Exports<'knip/dist/types/config'>;
}
declare module 'knip/dist/types/dependency-graph.js' {
  declare module.exports: $Exports<'knip/dist/types/dependency-graph'>;
}
declare module 'knip/dist/types/exports.js' {
  declare module.exports: $Exports<'knip/dist/types/exports'>;
}
declare module 'knip/dist/types/imports.js' {
  declare module.exports: $Exports<'knip/dist/types/imports'>;
}
declare module 'knip/dist/types/issues.js' {
  declare module.exports: $Exports<'knip/dist/types/issues'>;
}
declare module 'knip/dist/types/package-json.js' {
  declare module.exports: $Exports<'knip/dist/types/package-json'>;
}
declare module 'knip/dist/types/PluginNames.js' {
  declare module.exports: $Exports<'knip/dist/types/PluginNames'>;
}
declare module 'knip/dist/types/project.js' {
  declare module.exports: $Exports<'knip/dist/types/project'>;
}
declare module 'knip/dist/types/workspace.js' {
  declare module.exports: $Exports<'knip/dist/types/workspace'>;
}
declare module 'knip/dist/typescript/ast-helpers.js' {
  declare module.exports: $Exports<'knip/dist/typescript/ast-helpers'>;
}
declare module 'knip/dist/typescript/create-hosts.js' {
  declare module.exports: $Exports<'knip/dist/typescript/create-hosts'>;
}
declare module 'knip/dist/typescript/find-internal-references.js' {
  declare module.exports: $Exports<'knip/dist/typescript/find-internal-references'>;
}
declare module 'knip/dist/typescript/get-imports-and-exports.js' {
  declare module.exports: $Exports<'knip/dist/typescript/get-imports-and-exports'>;
}
declare module 'knip/dist/typescript/resolve-module-names.js' {
  declare module.exports: $Exports<'knip/dist/typescript/resolve-module-names'>;
}
declare module 'knip/dist/typescript/SourceFile.js' {
  declare module.exports: $Exports<'knip/dist/typescript/SourceFile'>;
}
declare module 'knip/dist/typescript/SourceFileManager.js' {
  declare module.exports: $Exports<'knip/dist/typescript/SourceFileManager'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/importCall.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports/importCall'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/importType.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports/importType'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/index' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/index.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/jsDocType.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports/jsDocType'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/requireCall.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports/requireCall'>;
}
declare module 'knip/dist/typescript/visitors/dynamic-imports/resolveCall.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/dynamic-imports/resolveCall'>;
}
declare module 'knip/dist/typescript/visitors/exports/exportAssignment.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports/exportAssignment'>;
}
declare module 'knip/dist/typescript/visitors/exports/exportDeclaration.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports/exportDeclaration'>;
}
declare module 'knip/dist/typescript/visitors/exports/exportKeyword.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports/exportKeyword'>;
}
declare module 'knip/dist/typescript/visitors/exports/exportsAccessExpression.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports/exportsAccessExpression'>;
}
declare module 'knip/dist/typescript/visitors/exports/index' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports'>;
}
declare module 'knip/dist/typescript/visitors/exports/index.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports'>;
}
declare module 'knip/dist/typescript/visitors/exports/moduleExportsAccessExpression.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/exports/moduleExportsAccessExpression'>;
}
declare module 'knip/dist/typescript/visitors/helpers.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/helpers'>;
}
declare module 'knip/dist/typescript/visitors/imports/importDeclaration.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/imports/importDeclaration'>;
}
declare module 'knip/dist/typescript/visitors/imports/importEqualsDeclaration.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/imports/importEqualsDeclaration'>;
}
declare module 'knip/dist/typescript/visitors/imports/index' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/imports'>;
}
declare module 'knip/dist/typescript/visitors/imports/index.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/imports'>;
}
declare module 'knip/dist/typescript/visitors/imports/reExportDeclaration.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/imports/reExportDeclaration'>;
}
declare module 'knip/dist/typescript/visitors/index' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors'>;
}
declare module 'knip/dist/typescript/visitors/index.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors'>;
}
declare module 'knip/dist/typescript/visitors/scripts/bun.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/scripts/bun'>;
}
declare module 'knip/dist/typescript/visitors/scripts/execa.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/scripts/execa'>;
}
declare module 'knip/dist/typescript/visitors/scripts/index' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/scripts'>;
}
declare module 'knip/dist/typescript/visitors/scripts/index.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/scripts'>;
}
declare module 'knip/dist/typescript/visitors/scripts/zx.js' {
  declare module.exports: $Exports<'knip/dist/typescript/visitors/scripts/zx'>;
}
declare module 'knip/dist/util/array.js' {
  declare module.exports: $Exports<'knip/dist/util/array'>;
}
declare module 'knip/dist/util/cli-arguments.js' {
  declare module.exports: $Exports<'knip/dist/util/cli-arguments'>;
}
declare module 'knip/dist/util/create-workspace-graph.js' {
  declare module.exports: $Exports<'knip/dist/util/create-workspace-graph'>;
}
declare module 'knip/dist/util/debug.js' {
  declare module.exports: $Exports<'knip/dist/util/debug'>;
}
declare module 'knip/dist/util/dependency-graph.js' {
  declare module.exports: $Exports<'knip/dist/util/dependency-graph'>;
}
declare module 'knip/dist/util/empty.js' {
  declare module.exports: $Exports<'knip/dist/util/empty'>;
}
declare module 'knip/dist/util/errors.js' {
  declare module.exports: $Exports<'knip/dist/util/errors'>;
}
declare module 'knip/dist/util/file-entry-cache.js' {
  declare module.exports: $Exports<'knip/dist/util/file-entry-cache'>;
}
declare module 'knip/dist/util/fs.js' {
  declare module.exports: $Exports<'knip/dist/util/fs'>;
}
declare module 'knip/dist/util/get-included-issue-types.js' {
  declare module.exports: $Exports<'knip/dist/util/get-included-issue-types'>;
}
declare module 'knip/dist/util/get-referenced-inputs.js' {
  declare module.exports: $Exports<'knip/dist/util/get-referenced-inputs'>;
}
declare module 'knip/dist/util/git.js' {
  declare module.exports: $Exports<'knip/dist/util/git'>;
}
declare module 'knip/dist/util/glob-core.js' {
  declare module.exports: $Exports<'knip/dist/util/glob-core'>;
}
declare module 'knip/dist/util/glob.js' {
  declare module.exports: $Exports<'knip/dist/util/glob'>;
}
declare module 'knip/dist/util/has-strictly-ns-references.js' {
  declare module.exports: $Exports<'knip/dist/util/has-strictly-ns-references'>;
}
declare module 'knip/dist/util/input.js' {
  declare module.exports: $Exports<'knip/dist/util/input'>;
}
declare module 'knip/dist/util/is-identifier-referenced.js' {
  declare module.exports: $Exports<'knip/dist/util/is-identifier-referenced'>;
}
declare module 'knip/dist/util/jiti.js' {
  declare module.exports: $Exports<'knip/dist/util/jiti'>;
}
declare module 'knip/dist/util/loader.js' {
  declare module.exports: $Exports<'knip/dist/util/loader'>;
}
declare module 'knip/dist/util/log.js' {
  declare module.exports: $Exports<'knip/dist/util/log'>;
}
declare module 'knip/dist/util/map-workspaces.js' {
  declare module.exports: $Exports<'knip/dist/util/map-workspaces'>;
}
declare module 'knip/dist/util/modules.js' {
  declare module.exports: $Exports<'knip/dist/util/modules'>;
}
declare module 'knip/dist/util/object.js' {
  declare module.exports: $Exports<'knip/dist/util/object'>;
}
declare module 'knip/dist/util/package-json.js' {
  declare module.exports: $Exports<'knip/dist/util/package-json'>;
}
declare module 'knip/dist/util/package-name.js' {
  declare module.exports: $Exports<'knip/dist/util/package-name'>;
}
declare module 'knip/dist/util/path.js' {
  declare module.exports: $Exports<'knip/dist/util/path'>;
}
declare module 'knip/dist/util/Performance.js' {
  declare module.exports: $Exports<'knip/dist/util/Performance'>;
}
declare module 'knip/dist/util/plugin-config.js' {
  declare module.exports: $Exports<'knip/dist/util/plugin-config'>;
}
declare module 'knip/dist/util/plugin.js' {
  declare module.exports: $Exports<'knip/dist/util/plugin'>;
}
declare module 'knip/dist/util/regex.js' {
  declare module.exports: $Exports<'knip/dist/util/regex'>;
}
declare module 'knip/dist/util/remove-export.js' {
  declare module.exports: $Exports<'knip/dist/util/remove-export'>;
}
declare module 'knip/dist/util/reporter.js' {
  declare module.exports: $Exports<'knip/dist/util/reporter'>;
}
declare module 'knip/dist/util/require.js' {
  declare module.exports: $Exports<'knip/dist/util/require'>;
}
declare module 'knip/dist/util/resolve.js' {
  declare module.exports: $Exports<'knip/dist/util/resolve'>;
}
declare module 'knip/dist/util/serialize.js' {
  declare module.exports: $Exports<'knip/dist/util/serialize'>;
}
declare module 'knip/dist/util/tag.js' {
  declare module.exports: $Exports<'knip/dist/util/tag'>;
}
declare module 'knip/dist/util/to-source-path.js' {
  declare module.exports: $Exports<'knip/dist/util/to-source-path'>;
}
declare module 'knip/dist/util/trace.js' {
  declare module.exports: $Exports<'knip/dist/util/trace'>;
}
declare module 'knip/dist/util/tsconfig-loader.js' {
  declare module.exports: $Exports<'knip/dist/util/tsconfig-loader'>;
}
declare module 'knip/dist/util/unwrap-function.js' {
  declare module.exports: $Exports<'knip/dist/util/unwrap-function'>;
}
declare module 'knip/dist/util/watch.js' {
  declare module.exports: $Exports<'knip/dist/util/watch'>;
}
declare module 'knip/dist/util/workspace.js' {
  declare module.exports: $Exports<'knip/dist/util/workspace'>;
}
declare module 'knip/dist/version.js' {
  declare module.exports: $Exports<'knip/dist/version'>;
}
declare module 'knip/dist/WorkspaceWorker.js' {
  declare module.exports: $Exports<'knip/dist/WorkspaceWorker'>;
}
declare module 'knip/vendor/bash-parser/index' {
  declare module.exports: $Exports<'knip/vendor/bash-parser'>;
}
declare module 'knip/vendor/bash-parser/index.js' {
  declare module.exports: $Exports<'knip/vendor/bash-parser'>;
}
