// flow-typed signature: 35ef0c799633305259b27c60633b4fd9
// flow-typed version: <<STUB>>/react-router_v7.1.2/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/dist/development/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/development' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/lib/types/route-module' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/production' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/lib/types/route-module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/dist/development/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/development/dom-export'>;
}
declare module 'react-router/dist/development/index' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/index.js' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/lib/types/route-module.js' {
  declare module.exports: $Exports<'react-router/dist/development/lib/types/route-module'>;
}
declare module 'react-router/dist/production/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/production/dom-export'>;
}
declare module 'react-router/dist/production/index' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/index.js' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/lib/types/route-module.js' {
  declare module.exports: $Exports<'react-router/dist/production/lib/types/route-module'>;
}
