// flow-typed signature: c7465c18a59a8d578964ed0e38d8da6a
// flow-typed version: <<STUB>>/rimraf_v^6.0.1/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rimraf/dist/commonjs/default-tmp' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/fix-eperm' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/fs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/ignore-enoent' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/opt-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/path-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/platform' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/readdir-or-error' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/retry-busy' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/rimraf-manual' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/rimraf-move-remove' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/rimraf-native' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/rimraf-posix' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/rimraf-windows' {
  declare module.exports: any;
}

declare module 'rimraf/dist/commonjs/use-native' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/default-tmp' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/fix-eperm' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/fs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/ignore-enoent' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/opt-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/path-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/platform' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/readdir-or-error' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/retry-busy' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/rimraf-manual' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/rimraf-move-remove' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/rimraf-native' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/rimraf-posix' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/rimraf-windows' {
  declare module.exports: any;
}

declare module 'rimraf/dist/esm/use-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rimraf/dist/commonjs/default-tmp.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/default-tmp'>;
}
declare module 'rimraf/dist/commonjs/fix-eperm.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/fix-eperm'>;
}
declare module 'rimraf/dist/commonjs/fs.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/fs'>;
}
declare module 'rimraf/dist/commonjs/ignore-enoent.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/ignore-enoent'>;
}
declare module 'rimraf/dist/commonjs/index' {
  declare module.exports: $Exports<'rimraf/dist/commonjs'>;
}
declare module 'rimraf/dist/commonjs/index.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs'>;
}
declare module 'rimraf/dist/commonjs/opt-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/opt-arg'>;
}
declare module 'rimraf/dist/commonjs/path-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/path-arg'>;
}
declare module 'rimraf/dist/commonjs/platform.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/platform'>;
}
declare module 'rimraf/dist/commonjs/readdir-or-error.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/readdir-or-error'>;
}
declare module 'rimraf/dist/commonjs/retry-busy.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/retry-busy'>;
}
declare module 'rimraf/dist/commonjs/rimraf-manual.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/rimraf-manual'>;
}
declare module 'rimraf/dist/commonjs/rimraf-move-remove.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/rimraf-move-remove'>;
}
declare module 'rimraf/dist/commonjs/rimraf-native.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/rimraf-native'>;
}
declare module 'rimraf/dist/commonjs/rimraf-posix.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/rimraf-posix'>;
}
declare module 'rimraf/dist/commonjs/rimraf-windows.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/rimraf-windows'>;
}
declare module 'rimraf/dist/commonjs/use-native.js' {
  declare module.exports: $Exports<'rimraf/dist/commonjs/use-native'>;
}
declare module 'rimraf/dist/esm/default-tmp.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/default-tmp'>;
}
declare module 'rimraf/dist/esm/fix-eperm.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/fix-eperm'>;
}
declare module 'rimraf/dist/esm/fs.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/fs'>;
}
declare module 'rimraf/dist/esm/ignore-enoent.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/ignore-enoent'>;
}
declare module 'rimraf/dist/esm/index' {
  declare module.exports: $Exports<'rimraf/dist/esm'>;
}
declare module 'rimraf/dist/esm/index.js' {
  declare module.exports: $Exports<'rimraf/dist/esm'>;
}
declare module 'rimraf/dist/esm/opt-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/opt-arg'>;
}
declare module 'rimraf/dist/esm/path-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/path-arg'>;
}
declare module 'rimraf/dist/esm/platform.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/platform'>;
}
declare module 'rimraf/dist/esm/readdir-or-error.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/readdir-or-error'>;
}
declare module 'rimraf/dist/esm/retry-busy.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/retry-busy'>;
}
declare module 'rimraf/dist/esm/rimraf-manual.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/rimraf-manual'>;
}
declare module 'rimraf/dist/esm/rimraf-move-remove.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/rimraf-move-remove'>;
}
declare module 'rimraf/dist/esm/rimraf-native.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/rimraf-native'>;
}
declare module 'rimraf/dist/esm/rimraf-posix.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/rimraf-posix'>;
}
declare module 'rimraf/dist/esm/rimraf-windows.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/rimraf-windows'>;
}
declare module 'rimraf/dist/esm/use-native.js' {
  declare module.exports: $Exports<'rimraf/dist/esm/use-native'>;
}
