// flow-typed signature: 9c7bed8063b766b0c7729221b4fd462d
// flow-typed version: <<STUB>>/storybook-addon-render-modes_v^0.0.11/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-render-modes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-render-modes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-render-modes/dist' {
  declare module.exports: any;
}

declare module 'storybook-addon-render-modes/dist/manager' {
  declare module.exports: any;
}

declare module 'storybook-addon-render-modes/dist/preview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-render-modes/dist/index' {
  declare module.exports: $Exports<'storybook-addon-render-modes/dist'>;
}
declare module 'storybook-addon-render-modes/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-render-modes/dist'>;
}
declare module 'storybook-addon-render-modes/dist/manager.js' {
  declare module.exports: $Exports<'storybook-addon-render-modes/dist/manager'>;
}
declare module 'storybook-addon-render-modes/dist/preview.js' {
  declare module.exports: $Exports<'storybook-addon-render-modes/dist/preview'>;
}
