// flow-typed signature: 539a5ab6af2956567fd43073053e77f7
// flow-typed version: <<STUB>>/stylelint-config-hudochenkov_v^11.0.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-hudochenkov'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-hudochenkov' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-hudochenkov/full' {
  declare module.exports: any;
}

declare module 'stylelint-config-hudochenkov/limit-language-features' {
  declare module.exports: any;
}

declare module 'stylelint-config-hudochenkov/order' {
  declare module.exports: any;
}

declare module 'stylelint-config-hudochenkov/possible-errors' {
  declare module.exports: any;
}

declare module 'stylelint-config-hudochenkov/stylistic-issues' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-hudochenkov/full.js' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov/full'>;
}
declare module 'stylelint-config-hudochenkov/index' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov'>;
}
declare module 'stylelint-config-hudochenkov/index.js' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov'>;
}
declare module 'stylelint-config-hudochenkov/limit-language-features.js' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov/limit-language-features'>;
}
declare module 'stylelint-config-hudochenkov/order.js' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov/order'>;
}
declare module 'stylelint-config-hudochenkov/possible-errors.js' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov/possible-errors'>;
}
declare module 'stylelint-config-hudochenkov/stylistic-issues.js' {
  declare module.exports: $Exports<'stylelint-config-hudochenkov/stylistic-issues'>;
}
