// flow-typed signature: e4c934ffbfd1b69e5b8fc1b5158a7a2b
// flow-typed version: <<STUB>>/stylelint-config-clean-order_v^7.0.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-clean-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-clean-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-clean-order/error' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/config' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/appearance' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/box-model' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/interaction' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/layout' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/positioning' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/svg-presentation' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/transition' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/src/groups/typography' {
  declare module.exports: any;
}

declare module 'stylelint-config-clean-order/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-clean-order/error.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/error'>;
}
declare module 'stylelint-config-clean-order/src/config.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/config'>;
}
declare module 'stylelint-config-clean-order/src/groups/appearance.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/appearance'>;
}
declare module 'stylelint-config-clean-order/src/groups/box-model.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/box-model'>;
}
declare module 'stylelint-config-clean-order/src/groups/interaction.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/interaction'>;
}
declare module 'stylelint-config-clean-order/src/groups/layout.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/layout'>;
}
declare module 'stylelint-config-clean-order/src/groups/positioning.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/positioning'>;
}
declare module 'stylelint-config-clean-order/src/groups/svg-presentation.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/svg-presentation'>;
}
declare module 'stylelint-config-clean-order/src/groups/transition.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/transition'>;
}
declare module 'stylelint-config-clean-order/src/groups/typography.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/src/groups/typography'>;
}
declare module 'stylelint-config-clean-order/warning.js' {
  declare module.exports: $Exports<'stylelint-config-clean-order/warning'>;
}
