// flow-typed signature: 8c771d3fb46b7663a438a392765e81a1
// flow-typed version: <<STUB>>/stylelint_v16.13.2/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
