// flow-typed signature: 8614386817a0a21bc7062e1c70941600
// flow-typed version: <<STUB>>/workbox-cacheable-response_v^7.3.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-cacheable-response'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-cacheable-response' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-cacheable-response/_version' {
  declare module.exports: any;
}

declare module 'workbox-cacheable-response/build/workbox-cacheable-response.dev' {
  declare module.exports: any;
}

declare module 'workbox-cacheable-response/build/workbox-cacheable-response.prod' {
  declare module.exports: any;
}

declare module 'workbox-cacheable-response/CacheableResponse' {
  declare module.exports: any;
}

declare module 'workbox-cacheable-response/CacheableResponsePlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-cacheable-response/_version.js' {
  declare module.exports: $Exports<'workbox-cacheable-response/_version'>;
}
declare module 'workbox-cacheable-response/build/workbox-cacheable-response.dev.js' {
  declare module.exports: $Exports<'workbox-cacheable-response/build/workbox-cacheable-response.dev'>;
}
declare module 'workbox-cacheable-response/build/workbox-cacheable-response.prod.js' {
  declare module.exports: $Exports<'workbox-cacheable-response/build/workbox-cacheable-response.prod'>;
}
declare module 'workbox-cacheable-response/CacheableResponse.js' {
  declare module.exports: $Exports<'workbox-cacheable-response/CacheableResponse'>;
}
declare module 'workbox-cacheable-response/CacheableResponsePlugin.js' {
  declare module.exports: $Exports<'workbox-cacheable-response/CacheableResponsePlugin'>;
}
declare module 'workbox-cacheable-response/index' {
  declare module.exports: $Exports<'workbox-cacheable-response'>;
}
declare module 'workbox-cacheable-response/index.js' {
  declare module.exports: $Exports<'workbox-cacheable-response'>;
}
