// flow-typed signature: ce50a38c995ee5198ecabb355711b44f
// flow-typed version: <<STUB>>/workbox-strategies_v^7.3.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-strategies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-strategies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-strategies/_version' {
  declare module.exports: any;
}

declare module 'workbox-strategies/build/workbox-strategies.dev' {
  declare module.exports: any;
}

declare module 'workbox-strategies/build/workbox-strategies.prod' {
  declare module.exports: any;
}

declare module 'workbox-strategies/CacheFirst' {
  declare module.exports: any;
}

declare module 'workbox-strategies/CacheOnly' {
  declare module.exports: any;
}

declare module 'workbox-strategies/NetworkFirst' {
  declare module.exports: any;
}

declare module 'workbox-strategies/NetworkOnly' {
  declare module.exports: any;
}

declare module 'workbox-strategies/plugins/cacheOkAndOpaquePlugin' {
  declare module.exports: any;
}

declare module 'workbox-strategies/StaleWhileRevalidate' {
  declare module.exports: any;
}

declare module 'workbox-strategies/Strategy' {
  declare module.exports: any;
}

declare module 'workbox-strategies/StrategyHandler' {
  declare module.exports: any;
}

declare module 'workbox-strategies/utils/messages' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-strategies/_version.js' {
  declare module.exports: $Exports<'workbox-strategies/_version'>;
}
declare module 'workbox-strategies/build/workbox-strategies.dev.js' {
  declare module.exports: $Exports<'workbox-strategies/build/workbox-strategies.dev'>;
}
declare module 'workbox-strategies/build/workbox-strategies.prod.js' {
  declare module.exports: $Exports<'workbox-strategies/build/workbox-strategies.prod'>;
}
declare module 'workbox-strategies/CacheFirst.js' {
  declare module.exports: $Exports<'workbox-strategies/CacheFirst'>;
}
declare module 'workbox-strategies/CacheOnly.js' {
  declare module.exports: $Exports<'workbox-strategies/CacheOnly'>;
}
declare module 'workbox-strategies/index' {
  declare module.exports: $Exports<'workbox-strategies'>;
}
declare module 'workbox-strategies/index.js' {
  declare module.exports: $Exports<'workbox-strategies'>;
}
declare module 'workbox-strategies/NetworkFirst.js' {
  declare module.exports: $Exports<'workbox-strategies/NetworkFirst'>;
}
declare module 'workbox-strategies/NetworkOnly.js' {
  declare module.exports: $Exports<'workbox-strategies/NetworkOnly'>;
}
declare module 'workbox-strategies/plugins/cacheOkAndOpaquePlugin.js' {
  declare module.exports: $Exports<'workbox-strategies/plugins/cacheOkAndOpaquePlugin'>;
}
declare module 'workbox-strategies/StaleWhileRevalidate.js' {
  declare module.exports: $Exports<'workbox-strategies/StaleWhileRevalidate'>;
}
declare module 'workbox-strategies/Strategy.js' {
  declare module.exports: $Exports<'workbox-strategies/Strategy'>;
}
declare module 'workbox-strategies/StrategyHandler.js' {
  declare module.exports: $Exports<'workbox-strategies/StrategyHandler'>;
}
declare module 'workbox-strategies/utils/messages.js' {
  declare module.exports: $Exports<'workbox-strategies/utils/messages'>;
}
