// flow-typed signature: c2a10a0eb48f1b90e9e21b6a1019261c
// flow-typed version: <<STUB>>/@babel/plugin-syntax-import-attributes_v^7.26.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-import-attributes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-import-attributes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-import-attributes/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-import-attributes/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-import-attributes/lib'>;
}
declare module '@babel/plugin-syntax-import-attributes/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-import-attributes/lib'>;
}
