// flow-typed signature: e98df7c202d5170a132e50331bcac45d
// flow-typed version: <<STUB>>/@arpitmalik832/react-js-rollup-library_v0.0.1-alpha.5/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@arpitmalik832/react-js-rollup-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@arpitmalik832/react-js-rollup-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/lg32/standardAccount.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/rg24/systemActionABCKeypad.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/sm16/systemAdd.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/lib' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/lg32/standardAccount.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/rg24/systemActionABCKeypad.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/sm16/systemAdd.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/lg32/standardAccount.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/lg32/standardAccount.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/rg24/systemActionABCKeypad.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/rg24/systemActionABCKeypad.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/sm16/systemAdd.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/sm16/systemAdd.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/lib.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/lib'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/lg32/standardAccount.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/lg32/standardAccount.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/rg24/systemActionABCKeypad.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/rg24/systemActionABCKeypad.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/sm16/systemAdd.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/sm16/systemAdd.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/lib.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/lib'>;
}
