// flow-typed signature: e0b48b5e8ae981ba108ed39bb5bf4481
// flow-typed version: <<STUB>>/@svgr/webpack_v^8.1.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/webpack/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/webpack/dist/index' {
  declare module.exports: $Exports<'@svgr/webpack/dist'>;
}
declare module '@svgr/webpack/dist/index.js' {
  declare module.exports: $Exports<'@svgr/webpack/dist'>;
}
