// flow-typed signature: 82ba4a6ca374d8a62df7839fe6195801
// flow-typed version: <<STUB>>/@storybook/addon-a11y_v8.5.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-a11y/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/postinstall' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/preview' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-a11y/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist'>;
}
declare module '@storybook/addon-a11y/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist'>;
}
declare module '@storybook/addon-a11y/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/manager'>;
}
declare module '@storybook/addon-a11y/dist/postinstall.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/postinstall'>;
}
declare module '@storybook/addon-a11y/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/preview'>;
}
declare module '@storybook/addon-a11y/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/manager'>;
}
declare module '@storybook/addon-a11y/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/preview'>;
}
